### ISSUE TITLE
tranner.train() compile failed

### ISSUE THREAD

**Issue by liygzting** [graphcore/poptorch#10]
Error                                     Traceback (most recent call last)
<ipython-input-16-3435b262f1ae> in <module>
----> 1 trainer.train()

/usr/local/lib/python3.8/dist-packages/optimum/graphcore/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
    902         self._load_optimizer_and_scheduler(resume_from_checkpoint)
    903 
--> 904         self._compile_model(model, next(iter(train_dataloader)), log=True)
    905 
    906         # Train!

/usr/local/lib/python3.8/dist-packages/optimum/graphcore/trainer.py in _compile_model(self, model, sample_batch, log)
    373             model.compile(*sample_batch)
    374         else:
--> 375             model.compile(**sample_batch)
    376         duration_compilation = time.perf_counter() - start_compile
    377         if log:

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in compile(self, *args, **kwargs)
    750             )
    751         else:
--> 752             self._compile(in_tensors)
    753 
    754     @_impl.traceMethod("loadExecutable")

/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py in wrapper(self, *args, **kwargs)
    286         def wrapper(self, *args, **kwargs):
    287             with self._profiling.tracepoint(label):  # pylint: disable=protected-access
--> 288                 return func(self, *args, **kwargs)
    289 
    290         return wrapper

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in _compile(self, in_tensors)
    661         if not self.isCompiled():
    662             if self._options.Jit.trace_model:
--> 663                 self._executable = poptorch_core.compileWithTrace(*trace_args)
    664             else:
    665                 self._executable = self._compileWithDispatch(

Error: In poptorch/poptorch_err/include/poptorch_err/ExceptionHandling.hpp:76: 'popart_exception': Could not find loss tensor 'IdentityLoss:0' in main graph tensors
Error raised in:
  [0] popart::TrainingSession::createFromOnnxModel
  [1] Compiler::initSession
  [2] LowerToPopart::compile
  [3] compileWithTrace

**Comment by ariannas-graphcore** [comment]
Hi,

the exception you're hitting might be related to the large size of the ONNX graph you're working with: the model data cannot exceed 2GB - the maximum size of a Protobuf message. You can verify this by searching for a `maximum protobuf size` limit error message in the output. 

This large graphs issue can be worked around by saving tensor data externally at PopART level using `Builder::saveInitializersExternally` - please refer to the [PopART user guide](https://docs.graphcore.ai/projects/popart-user-guide/en/latest/api-cpp.html#_CPPv4N6popart7Builder26saveInitializersExternallyERKNSt6vectorI8TensorIdEERKNSt6stringE) for more details. Alternatively, you could use the PopART hidden option `opts._Popart.set("saveInitializersToFile", "initializers.bin")` to save the initialisers to a separate file, avoiding the profobuf size limit. 

Hope this helps, do not hesitate to get back to us should you have any follow-up questions.

Best,
Arianna

**Comment by liygzting** [comment]
thanks ,  
I set config error, now it works well
