### ISSUE TITLE
I want a pic look like this?how to get ?

### ISSUE THREAD

**Issue by daixiangzi** [graphcore/poptorch#4]
![image](https://user-images.githubusercontent.com/24811131/153990389-a5185230-d6d1-4e84-bb5d-fc449d6d1f4f.png)

**Comment by LRVerkin** [comment]
Hi daixiangzi, thank you for opening this issue. You've asked the same question in another repo, so I will close this issue and answer you at https://github.com/graphcore/tutorials/issues/8.
